### ISSUE TITLE
drl build linking error

### ISSUE THREAD

**Issue by bill4u** [carlosmccosta/dynamic_robot_localization#11]
I have installed: 
ros-kinetic-laserscan-to-pointcloud_1.0.0-0xenial_amd64.deb
ros-kinetic-pcl_1.8.1-0xenial_amd64.deb
ros-kinetic-pose-to-tf-publisher_1.0.0-0xenial_amd64.deb

then I build the drl and get the following error:
[ 98%] Linking CXX executable devel/lib/dynamic_robot_localization/drl_localization_node
devel/lib/libdrl_localization.so：对‘pcl::search::Search<pcl::PointXYZRGBNormal>::getName() const’未定义的引用
collect2: error: ld returned 1 exit status

what can I do to fix this problem

**Comment by bill4u** [comment]
Do I need to remove the system installed PCL and reinstall  ros-kinetic-pcl_1.8.1-0xenial_amd64.deb?

**Comment by bill4u** [comment]
solved.THX

**Comment by carlosmccosta** [comment]
Good morning :)

I packaged and configured my fork of pcl for overriding the system installation (this way you do not need to touch your installation of pcl).

The error you are getting probably has the same cause of [this one](
https://github.com/carlosmccosta/dynamic_robot_localization/issues/10#issuecomment-538740122).

I integrated the [commit](https://github.com/carlosmccosta/dynamic_robot_localization/commit/1b279877308a34ce4e526ab6e190ba67c1eb4a2e) that solved this issue from the melodic to the kinetic branch.
Please do git pull and see if it solves the linking error.

P.S.
I did not have this issue in Ubuntu 16, probably because I am using an upgraded version of gcc (7.4) while also using [catkin tools](https://catkin-tools.readthedocs.io/en/latest/migration.html).
