### ISSUE TITLE
the angle unit

### ISSUE THREAD

**Issue by sunrentao** [carlosmccosta/dynamic_robot_localization#16]
Hi Carlo, 

I am configuring the yaml file, can I know what is the unit of the "max_new_pose_diff_angle"?

Degree among 360° or rad among 2π?

Best regards
Sun Rentao

**Comment by carlosmccosta** [comment]
Hello :)

Unless stated otherwise, the units follow the ros convention (meters and radians):
https://github.com/carlosmccosta/dynamic_robot_localization/blob/melodic-devel/yaml/schema/drl_configs.yaml#L16
http://www.ros.org/reps/rep-0103.html

The class that uses this parameters is EuclideanTransformationValidator:
https://github.com/carlosmccosta/dynamic_robot_localization/blob/melodic-devel/src/transformation_validators/euclidean_transformation_validator.cpp#L56
https://github.com/carlosmccosta/dynamic_robot_localization/blob/melodic-devel/src/transformation_validators/euclidean_transformation_validator.cpp#L112

Which relies on angleShortestPath of the tf2::Quaternion class:
https://github.com/ros/geometry2/blob/melodic-devel/tf2/include/tf2/LinearMath/Quaternion.h#L220

The function angleShortestPath should return values between 0 and pi.

Have a nice day :)
