### ISSUE TITLE
implementation for hash storage of map

### ISSUE THREAD

**Issue by abylikhsanov** [carlosmccosta/dynamic_robot_localization#7]
Hi Carlos,

As the code for your library is quite substantial, can you please point the location where you use hash table to store the map (reference cloud) against which you perform ICP and get a faster convergence than k tree implementation?

Also, I saw your version of icp in PCL fork but how different is the PCL ICP implementation from this one (referring if we use k tree implementation)?
https://github.com/AndreaCensi/csm

**Comment by carlosmccosta** [comment]
Good afternoon,

I implemented the correspondence estimation using lookup tables in my pcl fork:
* [https://github.com/carlosmccosta/pcl/blob/master-all-pr/registration/include/pcl/registration/correspondence_estimation_lookup_table.h](https://github.com/carlosmccosta/pcl/blob/master-all-pr/registration/include/pcl/registration/correspondence_estimation_lookup_table.h)
* [https://github.com/carlosmccosta/pcl/blob/master-all-pr/registration/include/pcl/registration/impl/correspondence_estimation_lookup_table.hpp](https://github.com/carlosmccosta/pcl/blob/master-all-pr/registration/include/pcl/registration/impl/correspondence_estimation_lookup_table.hpp)

There are a lot of different ways to implement ICP, since each stage of the algorithm can have [different approaches](http://ais.informatik.uni-freiburg.de/teaching/ss12/robotics/slides/17-icp.pdf), for each of its main stages:
- Establishment of corresponding points in reference and sensor data, in which there are several ways to select what are the best pairs
- Rejection of bad correspondences according to a set of criteria
- Estimation of the transformation from the set of correspondences that minimizes a given cost function (usually least squares optimization)
- Check if current registration is acceptable (for stoping the loop)

You can see the convergence loop of the pcl icp here:
[https://github.com/carlosmccosta/pcl/blob/master-all-pr/registration/include/pcl/registration/impl/icp.hpp#L171](https://github.com/carlosmccosta/pcl/blob/master-all-pr/registration/include/pcl/registration/impl/icp.hpp#L171)

From it, you can see that this ICP implementation can be configured to use different versions for each stage that I mention above.

I haven't use yet the csm, so you will need to look at the documentation / code to compare it to the PCL implementation.
